# **Pandas_Numpy Learning**

# **Circle Area Calculator**

# **Instructions**

Create a class Circle with a constructor that takes the radius as input. Implement an instance method area() that returns the area of the circle rounded to 2 decimal places.



Take the value of pi as math.pi



Input Format:

A float: radius



Output Format:

A float: area of the circle, rounded to 2 decimal places



Sample Input:

3



# **Sample Output:**

28.27

In [ ]:
import math

# Taking input
r = float(input())

class Circle:
    # Write your code below
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        # Formula: π * r^2
        calc_area = math.pi * (self.radius ** 2)
        return round(calc_area, 2)

obj_circle = Circle(r)
circle_area = obj_circle.area()
# Print the output
print(circle_area)

# **Positive Number Validation**

# **Instructions**

You are required to implement a class Validator with a static method is_positive(n) that returns True if the given number n is positive (greater than 0), and False otherwise.



This exercise reinforces the use of static methods in Python classes. A static method is defined using the @staticmethod decorator and does not depend on instance-specific data.





Input Format:

A single integer n is provided as input



Output Format:

Print True if the number is positive, otherwise print False





Sample Input 1:

-5



# **Sample Output 1:**

False





Sample Input 2:

10



Sample Output 2:

True





Sample Input 3:

0



Sample Output 3:

False

In [ ]:
# Taking Input
n = int(input())

class Validator:
    # Write your code below
    @staticmethod
    def is_positive(number_value):
        return ( True if number_value > 0 else False )

print(Validator.is_positive(n))

# **Rectangle Comparison**

# **Instructions**

You are required to define a class Rectangle that represents a rectangle using its width and height. The class should have a method area() that returns the area of the rectangle.



After defining the class, your program should:

Read two pairs of integers from input, where each pair represents the width and height of a rectangle.
Create two Rectangle objects using the given dimensions.
Compare the areas of the two rectangles and print:
"Rect1" if the first rectangle has a larger area,
"Rect2" if the second rectangle has a larger area,
"Equal" if both have the same area.




Input Format:

Two lines of input.
Each line contains two integers: width and height of one rectangle.


Output Format:

A single line: "Rect1", "Rect2", or "Equal" depending on the comparison of the two rectangles' areas.





Sample Input 1:

3 4

2 6



# **Sample Output 1:**

Equal





Sample Input 2:

5 2

4 3



Sample Output 2:

Rect2





Sample Input 3:

7 3

2 9



Sample Output 3:

Rect1

In [ ]:
# Input has been taken for you
w1, h1 = map(int, input().split())
w2, h2 = map(int, input().split())

class Rectangle:
    def __init__(self, width, height):
        # Write your code here
        self.width = width
        self.height = height


    def area(self):
        # Write your code here
        return self.width * self.height

rect1 = Rectangle(w1, h1)
rect2 = Rectangle(w2, h2)

area1 = rect1.area()
area2 = rect2.area()

# Write your comparison logic here
if area1 > area2:
    print("Rect1")
elif area2 > area1:
    print("Rect2")
else:
    print("Equal")




# **Multipurpose Calculator**

# **Instructions**

You are required to implement a class Calculator with the following methods:

An instance method add(x, y) that returns the sum of x and y
A class method identity() that returns the string "I'm a Calculator"
A static method greet() that returns the string "Hello"




Input Format:

Two integers, each on a separate line.



Output Format:

Three lines of output:

The sum of the two integers.

The identity string.

The greet string.



Sample Input:

4

5



# **Sample Output:**

9  

I'm a Calculator  

Hello

In [ ]:
# Input has been taken for you
x = int(input())
y = int(input())

class Calculator:
    # Define all required methods here
    def add(self, x, y):
        return x + y

    @classmethod
    def identity(cls):
        return "I'm a Calculator"

    @staticmethod
    def greet():
        return "Hello"



# Expected method calls and printing of results
calc = Calculator()
print(calc.add(x, y))
print(Calculator.identity())
print(Calculator.greet())


# **Extracting Elements from Array**

# **Instructions**

From a given array, extract all the elements which are greater than 'm' and less than 'n' where 'm' and 'n' are integer values provided as input.



Input format

A list of integers on line one

Integer 'm' on line two

Integer 'n' on line three



Output format

1-D array containing integers greater than 'm' and smaller than 'n'



Test Case 1

Sample input

[1, 5, 9, 12, 15, 7, 12, 9]

6

12



# **Sample output**

[9 7 9]



Test Case 2

Sample input

[1, 5, 9, 12, 15, 7, 12, 9]

12

6



Sample output

[]

In [ ]:
# Do not edit this input processing section
import ast
import numpy as np
x = np.array(ast.literal_eval(input()))
m = int(input())
n = int(input())

# Write your code here
y = x[(x > m) & (x < n)]

# Do not edit this output section
print(y)

# **Replacing Elements in NumPy Array**

# **Instructions**


From the given NumPy array, replace all elements that are less than 'm' with 'm', and replace all elements that are greater than 'n' with 'n' where 'm' and 'n' are integer values provided as input.



Input format:

A NumPy array (as a list) on line 1

Integer m on line 2

Integer n on line 3



Output format:

A NumPy array where:

All elements < m are replaced with m

All elements > n are replaced with n



Test Case 1:

Sample input:

[2, 8, 15, 5, 20, 11, 3]

6

12



# **Sample output:**

[6 8 12 6 12 11 6]



Test Case 2:

Sample input:

[10, 12, 14, 16]

12

15



Sample output:

[12 12 14 15]

In [ ]:
import numpy as np
import ast

# Read and convert input list into NumPy array
arr = np.array(ast.literal_eval(input().strip()))

# Read m and n
m = int(input().strip())
n = int(input().strip())

# Write your logic below
arr[arr < m] = m
arr[arr > n] = n

# Print the resulting NumPy array
print(arr)

# **Extracting Elements at Even Indices**

# **Instructions**

From the given NumPy array, extract all elements that are located at even indices (0, 2, 4, …).



Input Format

A NumPy array (as a list) on line 1



Output Format

A NumPy array containing elements from all even index positions of the original array



Test Case 1

Sample Input

[4, 7, 9, 12, 15, 3, 8]



# **Sample Output**

[4 9 15 8]



Test Case 2

Sample Input

[10]



Sample Output

[10]

In [3]:
import numpy as np
import ast

# Read and convert input list into NumPy array
arr = np.array(ast.literal_eval(input().strip()))

# Write your logic below
result = arr[::2]

# Print the resulting NumPy array
print(result)

[4, 7, 9, 12, 15, 3, 8]
[ 4  9 15  8]


# **End....**