# **Pandas_Numpy Learning**

# **Array Learning**

In [8]:
import numpy as np

import pandas as pd

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.flatten()
arr.reshape(1, 3, 3)
arr[1, 2]
#arr[[:1, :2]]
arr[:1, :2]
arr[..., 1]
arr.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [15]:
#arr1 & arr2
#arr1.add(arr2)
#np.scalarsum(arr1, arr2)
np.add(arr1, arr2)

array([5, 7, 9])

In [11]:
arr1 = np.array([[1, 2, 3]])

arr2 = np.array([10, 20])

In [12]:
reshaped_arr1 = arr1.reshape(3, 1)
np.add(reshaped_arr1, arr2)

array([[11, 21],
       [12, 22],
       [13, 23]])

# **Bank Balance with Balance**

# **Instructions**

Create a BankAccount class with:



a constructor that takes name and balance
an instance method show_balance() that prints: "Name: <name>, Balance: <balance>"


Input Format:

Line 1: A string (name)
Line 2: A float (balance)


Output Format:

A single line:

"Name: <name>, Balance: <balance>"



Sample Input 1:

John

2500.5



# **Sample Output 1:**

Name: John, Balance: 2500.5



Sample Input 2:

Charlie

-150.75



Sample Output 2:

Name: Charlie, Balance: -150.75

In [ ]:
# Taking Inputs
name = input()
balance = float(input())

class BankAccount:
    # Write your code here
    def __init__(self, name, balance):
        self.name = name
        self.balance = balance

    def show_balance(self):
        print( f"Name: {self.name} , Balance: {self.balance}" )

# Create object and print result
aacount_balance = BankAccount(name, balance)
aacount_balance.show_balance()

# **Temperature Converter**

# **Instructions**

You are required to define a class Temperature that stores temperature in degrees Celsius. Implement a class method from_fahrenheit(f) that accepts a Fahrenheit temperature as input and returns a Temperature object representing the equivalent temperature in Celsius.



This exercise demonstrates the use of class methods, which are typically used as alternative constructors for a class.



Use the standard formula to convert Fahrenheit to Celsius:

C = ((F - 32) * 5) / 9



The converted Celsius value should be rounded to 2 decimal places.



Input Format:

A single floating-point number representing a temperature in Fahrenheit.



Output Format:

A single floating-point number representing the equivalent temperature in Celsius, rounded to 2 decimal places.





Sample Input 1:

98.6



# **Sample Output 1:**

37.0





Sample Input 2:

32



Sample Output 2:

0.0





Sample Input 3:

212



Sample Output 3:

100.0

In [ ]:
# Taking Input
f = float(input())

class Temperature:
    # Write your code below
    def __init__(self, celsius) :
        self.celsius = celsius

    @classmethod
    def from_fahrenheit(cls, f) :
        return cls(round((((f-32)*5)/9),2))

obj_temp = Temperature.from_fahrenheit(f)
# Output the Temperature in Celsius
print(obj_temp.celsius)



# **End....**