# **Pandas_Numpy Learning**

In [2]:
import numpy as np

In [28]:
arr_num = np.ones((5,5))
print(arr_num)
print(arr_num[1:3, 2:4] )


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]]


In [27]:
arr_num = np.array([ [0,0,0] , [0,0,0] , [0,0,0] ])
print(arr_num)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [38]:
import numpy as np

# Create a 5x5 matrix with different numbers
matrix_5x5 = np.arange(1, 26).reshape(5, 5)
print(matrix_5x5)
print(matrix_5x5[1:3, 1:3] )
print(matrix_5x5[1:-1, 1:-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8]
 [12 13]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [43]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = [[5, 6], [7, 8]]
print(np.append(a, b, axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [51]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([[7, 8], [9, 10]])
d = np.array([[11, 12], [13, 14]])

print("np.concatenate((a, b), axis = 0)")
print(np.concatenate((a, b), axis = 0))

print("np.concatenate((a2, b2), axis = 1)")
a2 = a.reshape(1, -1)
b2 = b.reshape(1, -1)
print(a)
print(a2)
print(np.concatenate((a2, b2), axis = 1))

print("np.concatenate((a3, b3), axis = 1)")
a3 = a.reshape(-1, 1)
b3 = b.reshape(-1, 1)
print(a)
print(a3)
print(np.concatenate((a3, b3), axis = 1))

np.concatenate((a, b), axis = 0)
[1 2 3 4 5 6]
np.concatenate((a2, b2), axis = 1)
[1 2 3]
[[1 2 3]]
[[1 2 3 4 5 6]]
np.concatenate((a3, b3), axis = 1)
[1 2 3]
[[1]
 [2]
 [3]]
[[1 4]
 [2 5]
 [3 6]]


In [52]:
np.concatenate((c, d), axis = 0)

array([[ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [53]:
np.concatenate((c, d), axis = 1)

array([[ 7,  8, 11, 12],
       [ 9, 10, 13, 14]])

In [4]:
arr = np.array([[1, 2], [3, 4]])

In [6]:
np.transpose(arr)

array([[1, 3],
       [2, 4]])

In [8]:
np.transpose(arr, (1, 0))

(2, 2)

In [13]:
import pandas as pd

# Example DataFrame with a categorical column
df = pd.DataFrame({'color': ['red', 'blue', 'green', 'red', 'blue']}, dtype='category')

# Describe the categorical column
print(df['color'].describe())

count        5
unique       3
top       blue
freq         2
Name: color, dtype: object
